### ISSUE TITLE
Decimal delimiters in non-English locale

### ISSUE THREAD

**Issue by Deflaktor** [KingEnderBrine/-RoR2-InLobbyConfig#1]
I have a German locale and in German decimals are delimited by comma and not dot. I.e. `3,6` instead of `3.6`

When I try to edit a float value in the InLobbyUi, I can only enter numbers in German locale with commas. But once I confirm the edit, it just removes the commas.
On the other hand if I try to enter the value `3.6` it will not allow me to write the dot symbol, since my German locale expects commas to be written.

**Comment by KingEnderBrine** [comment]
Thanks for the report, should be fixed now.
